"""
ATADA — Invoice PDF Generator (mock)
Generates a simple PDF receipt locally using ReportLab.
No real Israeli tax authority integration.
"""

import os
from datetime import datetime, timezone
from pathlib import Path
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

INVOICES_DIR = Path(__file__).resolve().parent.parent.parent / "invoices"


def generate_invoice_pdf(
    invoice_id: str,
    user_name: str,
    amount_agorot: int,
    description: str,
    currency: str = "ILS",
) -> str:
    """
    Generate a simple PDF invoice/receipt.
    Returns the file path of the generated PDF.
    """
    INVOICES_DIR.mkdir(exist_ok=True)
    filename = f"invoice_{invoice_id}.pdf"
    filepath = INVOICES_DIR / filename

    c = canvas.Canvas(str(filepath), pagesize=A4)
    width, height = A4

    # Header
    c.setFont("Helvetica-Bold", 24)
    c.drawString(30 * mm, height - 30 * mm, "ATADA")
    c.setFont("Helvetica", 10)
    c.drawString(30 * mm, height - 38 * mm, "Invoice / Receipt")

    # Invoice number
    c.setFont("Helvetica", 9)
    c.drawRightString(width - 30 * mm, height - 30 * mm, f"Invoice #: {invoice_id[:12]}")
    c.drawRightString(width - 30 * mm, height - 38 * mm, f"Date: {datetime.now(timezone.utc).strftime('%Y-%m-%d')}")

    # Divider
    c.setStrokeColorRGB(0.85, 0.85, 0.85)
    c.line(30 * mm, height - 45 * mm, width - 30 * mm, height - 45 * mm)

    # Bill to
    y = height - 60 * mm
    c.setFont("Helvetica-Bold", 10)
    c.drawString(30 * mm, y, "Bill To:")
    c.setFont("Helvetica", 10)
    c.drawString(30 * mm, y - 6 * mm, user_name or "Customer")

    # Line items
    y -= 25 * mm
    c.setFont("Helvetica-Bold", 9)
    c.drawString(30 * mm, y, "Description")
    c.drawRightString(width - 30 * mm, y, "Amount")
    c.line(30 * mm, y - 2 * mm, width - 30 * mm, y - 2 * mm)

    y -= 10 * mm
    c.setFont("Helvetica", 10)
    c.drawString(30 * mm, y, description or "Subscription")
    amount_str = f"{amount_agorot / 100:.2f} {currency}"
    c.drawRightString(width - 30 * mm, y, amount_str)

    # Total
    y -= 15 * mm
    c.line(30 * mm, y + 3 * mm, width - 30 * mm, y + 3 * mm)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(30 * mm, y, "Total:")
    c.drawRightString(width - 30 * mm, y, amount_str)

    # Footer
    c.setFont("Helvetica", 8)
    c.setFillColorRGB(0.5, 0.5, 0.5)
    c.drawString(30 * mm, 25 * mm, "This is a mock invoice generated by Atada for development purposes.")
    c.drawString(30 * mm, 20 * mm, "Not a valid tax document (Heshbonit Mas).")

    # Watermark
    c.saveState()
    c.setFont("Helvetica-Bold", 60)
    c.setFillColorRGB(0, 0, 0, 0.04)
    c.translate(width / 2, height / 2)
    c.rotate(45)
    c.drawCentredString(0, 0, "ATADA")
    c.restoreState()

    c.save()
    return str(filepath)
